name: CI/CD OCR-Bot-CRC

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      build_image:
        description: "Czy zbudować obraz Docker?"
        required: true
        default: "true"
        type: boolean
      operation:
        description: "Jaką operację wykonać?"
        required: true
        default: "Reinstall"
        type: choice
        options: [ Install, Uninstall, Reinstall ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ocr-bot-crc.sln

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Lint (dotnet format)
        run: dotnet format ocr-bot-crc.sln --verify-no-changes

      - name: Run unit tests
        run: dotnet test ocr-bot-crc.sln --no-restore --verbosity normal

  build:
    needs: test
    if: ${{ github.event.inputs.build_image }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/ocr-bot-crc:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ocr-bot-crc:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy / Uninstall
        run: |
          echo "Wybrana operacja: ${{ github.event.inputs.operation }}"
